version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ecommerce_api
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:@db:5432/ecommerce_api
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_NAME: ecommerce_api
      DATABASE_PORT: 5432
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

volumes:
  pgdata:
